{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.tsb",
    "module": "logging-starter",
    "version": "1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.2-SNAPSHOT.jar",
          "url": "logging-starter-1.2-SNAPSHOT.jar",
          "size": 1331,
          "sha512": "22f1ff8d6717c8f93439f3db23ff8c6f755c264dec316e21e21baf209c860beb3195275726cc47404c01a17ffaa1b5a9679da97101a161f35bcc110c2c017fc8",
          "sha256": "de26618697cb913754c81106bc1782955b62ad9619b05b22436cde139d48112c",
          "sha1": "0ee748e81aabaa5666b7612f74fc370a351bad2c",
          "md5": "51cce87818c5290e6ec3d8f49cafd61f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-starter-1.2-SNAPSHOT.jar",
          "url": "logging-starter-1.2-SNAPSHOT.jar",
          "size": 1331,
          "sha512": "22f1ff8d6717c8f93439f3db23ff8c6f755c264dec316e21e21baf209c860beb3195275726cc47404c01a17ffaa1b5a9679da97101a161f35bcc110c2c017fc8",
          "sha256": "de26618697cb913754c81106bc1782955b62ad9619b05b22436cde139d48112c",
          "sha1": "0ee748e81aabaa5666b7612f74fc370a351bad2c",
          "md5": "51cce87818c5290e6ec3d8f49cafd61f"
        }
      ]
    }
  ]
}
